### ISSUE TITLE
Poor performance

### ISSUE THREAD

**Issue by PEMapModder** [KillerBLS/Ghost-Hack-MCPE#6]
Hack Password:

It takes an average of 25000 seconds, i.e. a. 7 hours to break a 6-digit password. Users would find it useless.

**Comment by PEMapModder** [comment]
Need me to make a pull request to improve it? :P

**Comment by AndreyNazarchuk** [comment]
LOL

**Comment by AndreyNazarchuk** [comment]
Its Been 7 hours...

**Comment by Thunder33345** [comment]
Hello form 2016

**Comment by KillerBLS** [comment]
Код скрипта открыт, можешь использовать любую его часть для создания своего скрипта, Ghost Hack обновляться не будет.
